# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 337dda9de1a6e9bd6ea3907a9f12c263f3c20bfd033f43e0de5836a06b3dc03f2d810c79a0e923c8e17e2abb7d3512075f0209f13b7b2f90b87e292edadc45b4

test:
  secret_key_base: 227079b0e2192b975d54345e40b503125a401f26fb7e1463f726d023bef1766aac28c704f2c038e80a001c077a3537ce4aeedf0e2a96c7d8d8b00d201c1d863e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
